# Generated by Django 5.2.12 on 2026-03-23 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchange_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('book', 'requester'), name='unique_active_request_per_book_requester'),
        ),
    ]
