# Generated by Django 5.2.12 on 2026-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('reserved', 'Зарезервирована'), ('exchanged', 'Обменена')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
